### PR TITLE
feat: Added Wish list page

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
- Added the WishList page.
- Made the page fully responsive.
- Fixed the link to the ProductList page
- Fixed active links for the page as well as the Side Menu.

Preview link to the page - https://deploy-preview-4--bluekart.netlify.app/src/wishlist

### CODE REVIEW

**Review by shrey27 — APPROVED** [review]
good to merge

**Review by thegeorgenikhil — APPROVED** [review]
Good to merge!

**Comment by SadiqZak** [comment]
`@media only screen and (max-width: 700px) {
    .wishList-page-nav {
        justify-content: flex-end;
    } 
}
`
I happened to learn "flex-end" exists from your code XD

This is great. Good to merge.

**Review by SadiqZak — APPROVED** [review]
I just had one comment regarding the use of pixels in the media. Otherwise this looks good.

And its responsive too! Bonus points incoming...

**Comment by Devansu-Yadav** [comment]
> `@media only screen and (max-width: 700px) { .wishList-page-nav { justify-content: flex-end; } } ` I happened to learn "flex-end" exists from your code XD
> 
> This is great. Good to merge.

That's awesome! 🙌

**Pull request merged**
